
name: Minimal Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:


permissions:
  contents: read


jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install unzip
        if [ -f requirements.txt ]; then pip install -r requirements.txt .; fi
    - name: Download and install Proper
      run: |
        wget https://sourceforge.net/projects/proper-library/files/proper_v3.3.4_python.zip && unzip proper_v3.3.4_python.zip
        cd proper_v3.3.4_python/
        python -m pip install .
        cd ..        
    - name: Download and install Roman preflight
      run: |
        git clone https://github.com/roman-corgi/cgisim_cpp.git  
        cd cgisim_cpp/
        python -m pip install .
        cd ..    
    - name: Download and install eetc
      run: |
        git clone https://github.com/nasa-jpl/cgi-eetc.git  
        cd cgi-eetc/
        python -m pip install .
        cd ..        
    - name: Download and install CGISim
      run: |
        wget https://sourceforge.net/projects/cgisim/files/cgisim_v4.1.zip  && unzip  cgisim_v4.1.zip
        cd  cgisim_v4.1/
        python -m pip install .
        cd ..   
        
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Minimal test
      run: |
        pytest ./test/test_minimal.py
